[package]
name = "tempus"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "date_constructor_benchmark"
harness = false
